openapi: 3.0.1
info:
  title: Graph API for Access Package Assignments
  description: API to retrieve details of access package assignments, including user information and relationships with accessPackage, target, and assignmentPolicy.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Main API server

paths:
  /accessPackageAssignments:
    get:
      summary: Get access package assignments
      description: Retrieve details of access package assignments, including user information and relationships.
      responses:
        '200':
          description: A list of access package assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccessPackageAssignment'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    AccessPackageAssignment:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the assignment
        userId:
          type: string
          description: Unique identifier for the user
        userName:
          type: string
          description: Name of the user
        accessPackage:
          $ref: '#/components/schemas/AccessPackage'
        target:
          $ref: '#/components/schemas/Target'
        assignmentPolicy:
          $ref: '#/components/schemas/AssignmentPolicy'

    AccessPackage:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the access package
        name:
          type: string
          description: Name of the access package

    Target:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the target
        type:
          type: string
          description: Type of the target (e.g., group, application)

    AssignmentPolicy:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the assignment policy
        name:
          type: string
          description: Name of the assignment policy
