openapi: 3.0.1
info:
  title: Graph API for Access Package Assignments
  description: API to retrieve details of access package assignments, including user information and relationships with accessPackage, target, and assignmentPolicy.
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
    description: Graph API to get access assignments

paths:
  /accessPackageAssignments:
    get:
      summary: Get access package assignments
      description: Retrieve details of access package assignments, including user information and relationships.
      responses:
        '200':
          description: A list of access package assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccessPackageAssignment'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
